[MODIF] Check if ice is in the path

diff --git a/bin/HiC-Pro b/bin/HiC-Pro
--- a/bin/HiC-Pro
+++ b/bin/HiC-Pro
@@ -127,6 +127,15 @@ if [[ -z $INPUT || -z $OUTPUT || -z $CONF ]]; then
 fi
 
 
+## check if ice is in the PATH
+if [[ $MAKE_OPTS == "" || $MAKE_OPTS =~ "ice_norm" ]]; then
+    which ice > /dev/null
+    if [ $? != "0" ]; then
+	echo -e "Error: The 'ice' command is not in your path. Please check where the 'iced' python package has been installed and update your PATH !"
+	exit 1;
+    fi
+fi
+
 #####################
 ## Check Config file
 #####################
@@ -181,14 +190,6 @@ if [[ ! -z $ALLELE_SPECIFIC_SNP && ! -r $ALLELE_SPECIFIC_SNP ]]; then
     die "ALLELE_SPECIFIC_SNP $ALLELE_SPECIFIC_SNP not found. Exit"
 fi
 
-## check if ice is in the PATH
-if [[ $MAKE_OPTS =~ "ice_norm" ]]; then
-    which ice > /dev/null;
-    if [ $? != "0" ]; then
-	echo -e "The 'ice' command is not in your path. Please check where the 'iced' python package has been installed and update your PATH !"
-	exit 1;
-    fi
-fi
 #####################
 ## Check step option
 #####################
